"""Generate PyInstaller and Inno Setup version metadata from release.ini."""

from __future__ import annotations

import configparser
import re
import sys
import uuid
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RELEASE_FILE = ROOT / "release.ini"
CHANGELOG_FILE = ROOT / "docs" / "CHANGELOG.md"
OUTPUT_DIR = ROOT / "build"
VERSION_INFO_FILE = OUTPUT_DIR / "version_info.txt"
INNO_DEFINES_FILE = OUTPUT_DIR / "release-defines.iss"
REQUIRED_KEYS = (
    "version",
    "tag_prefix",
    "product_name",
    "product_slug",
    "exe_name",
    "publisher",
    "app_id",
)
SEMVER_RE = re.compile(r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$")
CHANGELOG_RELEASE_RE = re.compile(r"^##\s+\[([^\]]+)\]", re.MULTILINE)
SAFE_NAME_RE = re.compile(r"^[A-Za-z0-9._-]+$")
TAG_PREFIX_RE = re.compile(r"^[A-Za-z0-9._-]+$")


def load_release(path: Path = RELEASE_FILE) -> dict[str, str]:
    parser = configparser.ConfigParser(interpolation=None)
    if not parser.read(path, encoding="utf-8"):
        raise ValueError(f"release configuration not found: {path}")
    if "release" not in parser:
        raise ValueError("release.ini is missing the [release] section")
    values = {key: parser["release"].get(key, "").strip() for key in REQUIRED_KEYS}
    missing = [key for key, value in values.items() if not value]
    if missing:
        raise ValueError(f"release.ini has empty or missing keys: {', '.join(missing)}")
    unsafe = [
        key
        for key, value in values.items()
        if any(ord(character) < 32 or ord(character) == 127 for character in value)
    ]
    if unsafe:
        raise ValueError(f"release.ini values contain control characters: {', '.join(unsafe)}")
    match = SEMVER_RE.fullmatch(values["version"])
    if not match:
        raise ValueError("version must be SemVer in MAJOR.MINOR.PATCH form")
    for key in ("product_slug", "exe_name"):
        if not SAFE_NAME_RE.fullmatch(values[key]):
            raise ValueError(f"{key} may contain only letters, digits, dot, underscore, and hyphen")
    if not TAG_PREFIX_RE.fullmatch(values["tag_prefix"]):
        raise ValueError("tag_prefix may contain only letters, digits, dot, underscore, and hyphen")
    try:
        values["app_id"] = str(uuid.UUID(values["app_id"])).upper()
    except ValueError as exc:
        raise ValueError("app_id must be a valid GUID") from exc
    return values


def validate_changelog(version: str, tag_prefix: str, path: Path = CHANGELOG_FILE) -> None:
    text = path.read_text(encoding="utf-8")
    match = CHANGELOG_RELEASE_RE.search(text)
    if not match:
        raise ValueError(f"no release heading found in {path}")
    expected = f"{tag_prefix}{version}"
    if match.group(1) != expected:
        raise ValueError(
            f"release tag {expected} does not match latest CHANGELOG tag {match.group(1)}"
        )


def _quote(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def render_version_info(release: dict[str, str]) -> str:
    major, minor, patch = (int(part) for part in release["version"].split("."))
    version_tuple = f"({major}, {minor}, {patch}, 0)"
    product = _quote(release["product_name"])
    exe = _quote(release["exe_name"] + ".exe")
    publisher = _quote(release["publisher"])
    version = _quote(release["version"])
    return f"""# Generated by scripts/generate_version_info.py. Do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(filevers={version_tuple}, prodvers={version_tuple}, mask=0x3f,
    flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)),
  kids=[StringFileInfo([StringTable('040904B0', [
    StringStruct('CompanyName', '{publisher}'),
    StringStruct('FileDescription', '{product}'),
    StringStruct('FileVersion', '{version}'),
    StringStruct('InternalName', '{exe}'),
    StringStruct('OriginalFilename', '{exe}'),
    StringStruct('ProductName', '{product}'),
    StringStruct('ProductVersion', '{version}')
  ])]), VarFileInfo([VarStruct('Translation', [1033, 1200])])]
)
"""


def _inno_quote(value: str) -> str:
    return value.replace('"', '""')


def render_inno_defines(release: dict[str, str]) -> str:
    return "\n".join(
        [
            "; Generated by scripts/generate_version_info.py. Do not edit.",
            f'#define MyAppName "{_inno_quote(release["product_name"])}"',
            f'#define MyAppVersion "{release["version"]}"',
            f'#define MyAppPublisher "{_inno_quote(release["publisher"])}"',
            f'#define MyAppExeName "{release["exe_name"]}.exe"',
            f'#define MyProductSlug "{release["product_slug"]}"',
            f'#define MyAppId "{release["app_id"]}"',
            f'#define MyDistDir "..\\dist\\{release["exe_name"]}"',
            "",
        ]
    )


def generate() -> None:
    release = load_release()
    validate_changelog(release["version"], release["tag_prefix"])
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    VERSION_INFO_FILE.write_text(render_version_info(release), encoding="utf-8", newline="\n")
    INNO_DEFINES_FILE.write_text(render_inno_defines(release), encoding="utf-8", newline="\n")
    print(f"Generated release metadata for {release['version']}")


def main() -> int:
    try:
        generate()
    except (OSError, ValueError, configparser.Error) as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
